### ISSUE TITLE
pretrained classifier

### ISSUE THREAD

**Issue by dearkafka** [ju-leon/RetouchML#1]
Hi! Could you provide file linked in colab: RetouchML/models/no\_pca.keras ?

**Comment by ju-leon** [comment]
Hi,
you can find the classifier here:
https://drive.google.com/file/d/1--6jvVYGf1SCm4s72CBCSvYcJ6zoob0B/view?usp=sharing

Please keep in mind that this part of the process is still a WIP, so let me know if you have any other issues

**Comment by dearkafka** [comment]
sorry, took some time to respond.

thank you very much, it works pretty well. I had some problems with colab though, namely, there was a conflict of tensorflow graphs of stylegan and keras you provided. I made some changes and it works. https://colab.research.google.com/drive/18EUa2ciaqBUAguBVM1DLDrrTzNwOohWz?usp=sharing

**Comment by abekalarz** [comment]
Hi,

@ju-leon :) : I was trying to download your classifier from previous link (from 2-Nov-2020), but I've got info that this file is in your trash 
(https://drive.google.com/file/d/1--6jvVYGf1SCm4s72CBCSvYcJ6zoob0B/view?usp=sharing)

Are you able to upload and share this classifier one more time? :) Or even better: maybe you have trained your classifier for men too?

Currently I am testing your RetouchML and I am very interested in further results.
I will be very grateful for your help :)

Thanks in advance,
Adam

**Comment by ju-leon** [comment]
Hi Adam, 

Sorry, the link should work again now!
Unfortunately i didn't have time yet to to train the model for men, but it's definitely on my to-do list for the coming months.

Hope that helps.
Regards
Leon

**Comment by abekalarz** [comment]
> (...)
> Hope that helps.
> Regards
> Leon

Wow, @ju-leon thank you very much for such very fast reply! :) Yes, that helps me a lot! 

And no problem, I understand that it needs time... especially training ML-related things ;-) !

Have a nice day!
Best regards!

**Comment by abekalarz** [comment]
@ju-leon: Sorry for bothering you again, but maybe you know answer. I've uploaded your classificator, but unfortunately I've got below error:

OSError: SavedModel file does not exist at: /content/drive/My Drive/RetouchML/models/no_pca.keras/{saved_model.pbtxt|saved_model.pb}

Do you know why or where could I find missing .pbtxt or .pb file(s) ?

Thank you very much in advance! :)

**Comment by ju-leon** [comment]
Looks like that's a problem with your pathname.

no_pca.keras is a file not a directory, so the path you give to keras.models.load_model() should not end with a "/".

**Comment by abekalarz** [comment]
Thank you for your help @ju-leon ! It worked!

With regard to your earlier sentence:
> This classifier is only trained on women at the moment since I'm still in the process of creating a dataset for men.

Maybe do you have some instruction available on web how to train/create such .keras classifier? 

I am newbe in ML-related areas and I would be very happy to do such training by myself :) 
Thank you for your understanding.

**Comment by ju-leon** [comment]
It's a convolutional neural network performing regression on images.
It predicts a score for each image of a face that judges the quality of the image. 
Since I couldn't find any datasets judging image quality of portraits, i had to create my own. 
At the moment i only created that dataset for women, which is why i couldn't train the classifier on men yet.

If you'd like to train your own classifier, I'd suggest starting by finding or creating a dataset with the values you're looking for, and then training a neural network on that dataset.

**Comment by ekatiyar** [comment]
There's a dataset that provides labelled beauty data - https://github.com/HCIILAB/SCUT-FBP5500-Database-Release 

I was thinking of training a model with this data but I'm not certain how you encoded your custom data when training. Could you provide me some information about how I could get started?

**Comment by ju-leon** [comment]
The main problem with this dataset that the the latent vector representation for the images in this dataset is unknown.

In order to improve on the image quality, i make a prediction from latent vector -> image quality.
I then compute the gradient of the latent vector and follow the latent vector in the direction of the gradient. 
Translating the altered latent vector back to an image will result in an "improved" image.

So in oder to use the dataset, you'd have to translate all the images into latent vectors first. Then you could go ahead and train the model on the generated latent vectors.
So the model would predict:
latent vector -> beauty

Unfortunately encoding images into latent vectors is pretty slow. 
I might give it a try in the near future, but I'm pretty busy the next month.

If you'd like to have access to the dataset I created please contact me directly.
The dataset contains samples of around 1600 latent vectors with their respective "attractiveness".
